# Test your FastAPI endpoints

WEBSOCKET ws://192.168.31.93:8000/ws/192.168.31.93
Accept: application/json

###

GET http://192.168.31.93:3000/trigger_websocket_connection/
Accept: application/json

###
